test_task:
  name: cargo test 
  matrix:
    - container:
       image: rust:1.24.1
    - container:
       image: rust:latest
    - container:
       image: rustlang/rust:nightly
  env:
    # rustc 1.31.0-nightly 2018-10-20 on Travis reports ODR violations within
    # asan itself.
    # https://travis-ci.org/asomers/divbuf/jobs/447109902
    ASAN_OPTIONS: "detect_odr_violation=0"
  cargo_cache:
    folder: $CARGO_HOME/registry
  test_script:
    - cargo test
  asan_script:
    - if rustc --version | grep -q nightly; then
    -   env RUSTFLAGS="-Z sanitizer=address" cargo test --tests
    - fi
  before_cache_script: rm -rf $CARGO_HOME/registry/index

codecov_task:
  name: codecov 
  depends_on:
    - test
  environment:
    CODECOV_TOKEN: ENCRYPTED[54b6d5e41602073176c11bdb628e7534447fe06a87a3dfe620e984db929aacb35f26e611cc1e2e1eeae662b5cc5c5508]
    # Improves coverage accuracy
    RUSTFLAGS: "-C link-dead-code"
  matrix:
    - container:
       image: rust:latest
  cargo_cache:
    folder: $CARGO_HOME/registry
  setup_script:
    - apt-get -y update
    - apt-get -y install libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev
    - cargo install cargo-kcov
    - if [ ! -x $HOME/.cargo/bin/kcov ] || [ ! -f $HOME/.cargo/bin/kcov ]; then mkdir kcov && cd kcov && cargo kcov --print-install-kcov-sh | sh && cd - && rm -rf kcov; fi
  codecov_script:
    - cargo check       # Ensure Cargo.lock exists
    - cargo kcov --verbose -- --include-pattern='divbuf/src'
    - bash <(curl -s https://codecov.io/bash)
  before_cache_script: rm -rf $CARGO_HOME/registry/index

minver_task:
  name: minver
  depends_on:
    - test
  matrix:
    - container:
       image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
  test_script:
    - cargo update -Zminimal-versions
    - cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index
