test_task:
  matrix:
    - container:
       image: rust:1.80
    - container:
       image: rust:latest
    - container:
       image: rustlang/rust:nightly
  env:
    # rustc 1.31.0-nightly 2018-10-20 on Travis reports ODR violations within
    # asan itself.
    # https://travis-ci.org/asomers/divbuf/jobs/447109902
    ASAN_OPTIONS: "detect_odr_violation=0"
  cargo_cache:
    folder: $CARGO_HOME/registry
  test_script:
    - cargo test --all-features
  clippy_script:
    - if rustc --version | grep -q nightly; then
    -   rustup component add clippy
    -   cargo clippy --all-features --all-targets -- -D warnings
    - fi
  audit_script:
    - if rustc --version | grep -q nightly; then
    -   cargo install cargo-audit
    -   cargo audit
    - fi
  bench_script:
    - if rustc --version | grep -q nightly; then
    -   cargo test --all-features --bench '*'
    - fi
  fmt_script:
    - if rustc --version | grep -q nightly; then
    -   rustup component add rustfmt
    -   cargo fmt -- --check
    - fi
  asan_script:
    - if rustc --version | grep -q nightly; then
    -   env RUSTFLAGS="-Z sanitizer=address" cargo test --all-features --tests
    - fi
  before_cache_script: rm -rf $CARGO_HOME/registry/index

minver_task:
  depends_on:
    - test
  matrix:
    - container:
       image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
  test_script:
    - cargo update -Zminimal-versions
    - cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index
