[package]
name = "divbuf"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/asomers/divbuf"
description = """
Buffer object that can be recursively divided into smaller buffers
"""
categories = ["data-structures"]
keywords = ["buffers", "io", "zero-copy"]
exclude       = [
    ".gitignore",
]

[dependencies]

[dev-dependencies]
lazy_static = "1"

[[test]]
name = "functional"
path = "tests/test_divbuf.rs"

[[test]]
name = "thread_race"
path = "tests/thread_race.rs"
